### ISSUE TITLE
Birth Date in american format in Samsung Browser

### ISSUE THREAD

**Issue by Warner99** [Campus-Consult/MemberManager#140]
Even if the settings of the Samsung browser are set to german, the date of birth is presented in the MM/DD/YYYY format

**Comment by Alfer-Star** [comment]
I wanted to say we do not need to support samsnug browser, because it is rarely used and hould take it as an "known issue" ad acta,
but after I take into account ths satistsics: [Mobile Browser Usage](https://de.statista.com/statistik/daten/studie/184297/umfrage/marktanteile-mobiler-browser-bei-der-internetnutzung-in-deutschland-seit-2009/#:~:text=Im%20März%202022%20erreichte%20Chrome,Anteil%20von%2011%2C76%20Prozent.) You cannot ignore it, because it is one if the mobile browser user often uses. :O
A lot og people are to lazy to change their standard browser on Samsung Phones. :D
